### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by CodyRay** [crossplane-contrib/contribfest#2]
I was interested in using some of xfns as a starting point, but I observed that it appeared to be unlicensed. Would it be possible to add a license or clarify if there is an existing license? Thanks!

**Comment by jbw976** [comment]
Good catch @CodyRay! forgot to do that when we first started this repo 😊 

Everything in the repo is licensed under Apache 2. I just merged #3 so it's all official in the repo now.

Hope to see you at the next contribfest event in person at Kubecon too! 💪
